shop/urls.py
from django.urls import path, include
from django.contrib.staticfiles.urls import static
from rest_framework import routers

from . import views
from users import views as user_views
from sparta import settings

app_name = 'shop'

router = routers.DefaultRouter()
router.register('subscription', views.SubscriptionViewSet)
router.register('users', user_views.UserViewSet)

urlpatterns = [
    path('', views.home, name='home'),
    path('shop/', views.shop, name='shop'),
    path('user/cart/', views.cart, name='cart'),
    path('user/profile/<int:id>/', views.profile, name='profile'),
    path('subscription-check/', views.subscription_check, name='subscription-check'),
    path('checkout/', views.checkout, name='check-out'),
    path('training-programs/', views.train_constructor, name='train_constructor'),

    path('update-item/', views.update_item, name='update-item'),
    path('process-order/', views.process_order, name='process-order'),

    path('api/', include(router.urls)),
    path('api/subscription-search/', views.SubscriptionSearchListAPIView.as_view(), name='sub-search'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sparta/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('shop.urls')),
    path('accounts/', include('allauth.urls')),
    path('rest_auth/', include('rest_auth.urls')),
    path('rest_auth/registration/', include('rest_auth.registration.urls')),
    path('rest_framework/', include('rest_framework.urls')),
]

users/urls.py
from django.urls import path
from django.conf.urls import url
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

from . import views
from sparta import settings

app_name = 'users'

urlpatterns = [
    path('signup/', views.signup_form, name='signup'),
    path('login/', views.login_form, name='login'),


    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/models.py
import datetime

from django.db import models
from django.contrib.postgres.fields import ArrayField


class ProductType(models.Model):
    type_name = models.CharField(max_length=64)

    class Meta:
        verbose_name = 'Тип продукта'
        verbose_name_plural = 'Типы продуктов'

    def __str__(self):
        return str(self.type_name)


class Product(models.Model):
    name = models.CharField(max_length=64)
    product_type = models.ForeignKey(ProductType, on_delete=models.CASCADE)
    price = models.FloatField()
    weight = models.FloatField()
    portions = models.IntegerField()
    description = models.TextField(max_length=256, default=None)
    image = models.ImageField(upload_to="products")
    date = models.DateField(auto_now_add=True)
    digital = models.BooleanField(default=False, blank=True, null=True)

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'

    def __str__(self):
        return str(self.name)

    @property
    def imageURL(self):
        try:
            url = self.image.url
        except:
            url = ''
        return url


class Post(models.Model):
    title = models.CharField(max_length=64)
    text = models.TextField(max_length=1024)
    date = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'Пост/Новость'
        verbose_name_plural = 'Посты/Новости'

    def __str__(self):
        return str(self.title)

    def body(self):
        return self.text


class PriceList(models.Model):
    TYPES = (
        ('Одноразовая тренировка', 'Одноразовая тренировка'),
        ('Тренировки с тренером', 'Тренировки с тренером'),
        ('Неделя с тренером', 'Неделя с тренером'),
        ('Самостоятельные тренировки', 'Самостоятельные тренировки')
    )
    training_type = models.CharField(choices=TYPES, max_length=64)
    price = models.IntegerField()
    description_1 = models.CharField(max_length=64, blank=True, null=True)
    description_2 = models.CharField(max_length=64, blank=True, null=True)
    description_3 = models.CharField(max_length=64, blank=True, null=True)
    description_4 = models.CharField(max_length=64, blank=True, null=True)
    description_5 = models.CharField(max_length=64, blank=True, null=True)

    class Meta:
        verbose_name = 'Прайс-лист'
        verbose_name_plural = 'Прайс-листы'


class Order(models.Model):
    customer = models.ForeignKey('users.Customer', on_delete=models.SET_NULL, blank=True, null=True)
    date_ordered = models.DateTimeField(auto_now_add=True)
    complete = models.BooleanField(default=False, null=True, blank=True)
    transaction_id = models.CharField(max_length=256, null=True)

    class Meta:
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'

    def __str__(self):
        return str(self.id)

    @property
    def shipping(self):
        shipping = False
        orderitems = self.orderitem_set.all()
        print(orderitems)
        for i in orderitems:
            if not i.product.digital:
                shipping = True
        return shipping

    @property
    def get_cart_total(self):
        order_items = self.orderitem_set.all()
        total = sum([item.get_total for item in order_items])
        return total

    @property
    def get_cart_items(self):
        order_items = self.orderitem_set.all()
        total = sum([item.quantity for item in order_items])
        return total


class OrderItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, blank=True, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, blank=True, null=True)
    quantity = models.IntegerField(default=0, null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)
    digital = models.BooleanField(default=False)

    class Meta:
        verbose_name = 'Заказанный товар'
        verbose_name_plural = 'Заказанные товары'

    def __str__(self):
        return str(self.product)

    @property
    def get_total(self):
        total = self.product.price * self.quantity
        return total


class ShippingAddress(models.Model):
    customer = models.ForeignKey('users.Customer', on_delete=models.SET_NULL, blank=True, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, blank=True, null=True)
    city = models.CharField(max_length=256, blank=True, null=True)
    state = models.CharField(max_length=256, blank=True, null=True)
    address = models.CharField(max_length=256, blank=True, null=True)
    zip_code = models.CharField(max_length=64, blank=True, null=True)
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'Адрес доставки'
        verbose_name_plural = 'Адреса доставки'

    def __str__(self):
        return str(self.address)


def get_subscription_expired_date():
    return (datetime.datetime.now() + datetime.timedelta(30)).date()


class Subscription(models.Model):
    customer = models.ForeignKey('users.Customer', on_delete=models.CASCADE, blank=True, null=True)
    start_date = models.DateField(auto_now_add=True)
    end_date = models.DateField(default=get_subscription_expired_date)
    visits = models.PositiveIntegerField(default=12)
    visit_dates = ArrayField(models.DateField(), size=12, null=True, blank=True)
    is_active = models.BooleanField(default=True)

    class Meta:
        verbose_name = 'Абонемент'
        verbose_name_plural = 'Абонементы'
        unique_together = ('customer', 'end_date',)

shop/forms.py
from django import forms

from users.models import Profile


class EditProfileModelForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['name', 'surname', 'phone', 'birthday', 'image']

shop/views.py
import json
import datetime

from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_protect
from rest_framework.filters import SearchFilter
from rest_framework.generics import ListAPIView
from rest_framework.response import Response
from rest_framework import viewsets, status
from rest_framework.permissions import AllowAny
from django_filters.rest_framework import DjangoFilterBackend

from shop.filters import ProductFilter
from shop.models import *
from shop.serializers import SubscriptionSerializer
from shop.forms import EditProfileModelForm
from shop.services import cart_data, guest_order


def home(request):
    posts = Post.objects.order_by('date')[:3]
    prices = PriceList.objects.all()
    user_id = request.user.id
    context = {
        'posts': posts,
        'prices': prices,
        'user_id': user_id
    }
    return render(request, 'shop/home.html', context)


def train_constructor(request):
    return render(request, 'shop/train_construct.html')


@csrf_protect
def shop(request):
    user_id = request.user.id
    data = cart_data(request)
    cart_items = data['cart_items']

    products = Product.objects.all()
    product_filter = ProductFilter(request.POST, queryset=products)
    products = product_filter.qs
    context = {
        'products': products,
        'product_filter': product_filter,
        'cart_items': cart_items,
        'user_id': user_id
    }
    return render(request, 'shop/shop.html', context)


@csrf_protect
def cart(request):
    user_id = request.user.id

    data = cart_data(request)
    cart_items = data['cart_items']
    order = data['order']
    items = data['items']

    context = {
        'items': items,
        'order': order,
        'cart_items': cart_items,
        'user_id': user_id
    }
    return render(request, 'shop/cart.html', context)


def update_item(request):
    data = json.loads(request.body)
    product_id = data['productId']
    action = data['action']

    customer = request.user.customer
    product = Product.objects.get(id=product_id)
    order, created = Order.objects.get_or_create(customer=customer, complete=False)
    order_item, created = OrderItem.objects.get_or_create(order=order, product=product)

    if action == 'add':
        order_item.quantity = (order_item.quantity + 1)
    elif action == 'remove':
        order_item.quantity = (order_item.quantity - 1)

    order_item.save()

    if order_item.quantity <= 0:
        order_item.delete()

    return JsonResponse('Item was added', safe=False)


def checkout(request):
    user_id = request.user.id
    user = request.user
    data = cart_data(request)
    cart_items = data['cart_items']
    order = data['order']
    items = data['items']

    context = {
        'items': items,
        'order': order,
        'cart_items': cart_items,
        'user_id': user_id,
        'user': user,
    }
    return render(request, 'shop/checkout.html', context)


def process_order(request):
    transaction_id = datetime.datetime.now().timestamp()
    data = json.loads(request.body)

    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer=customer, complete=False)
    else:
        customer, order = guest_order(request, data)

    total_str = data['form']['total']
    total_str = total_str.replace(',', '.')
    total = float(total_str)
    order.transaction_id = transaction_id
    if total == order.get_cart_total:
        order.complete = True
    order.save()

    if order.shipping:
        ShippingAddress.objects.create(
            customer=customer,
            order=order,
            address=data['shipping']['address'],
            city=data['shipping']['city'],
            state=data['shipping']['state'],
            zip_code=data['shipping']['zipcode'],
        )

    return JsonResponse('Payment complete!', safe=False)


@csrf_protect
@login_required(login_url='users:login')
def profile(request, id):
    user_id = request.user.id
    if request.method == 'POST':
        form = EditProfileModelForm(request.POST, request.FILES, instance=request.user.profile)
        if form.is_valid():
            form.save()
            return redirect(f'/user/profile/{user_id}/')
    else:
        form = EditProfileModelForm(instance=request.user.profile)

    username = request.user.username
    name = request.user.profile.name
    surname = request.user.profile.surname
    age = 0
    if request.user.profile.birthday:
        age = int(datetime.datetime.today().year) - int(request.user.profile.birthday.year)

    visited_dates = []
    subscription = []
    if request.user.is_authenticated:
        customer = request.user.customer
        try:
            subscription = Subscription.objects.get(customer=customer)
            visited_dates = subscription.visit_dates
        except Subscription.DoesNotExist:
            visited_dates = ['У вас нет действующего абонемента']

    context = {
        'username': username,
        'subscription': subscription,
        'name': name,
        'surname': surname,
        'age': age,
        'dates': visited_dates,
        'update': form,
        'user_id': user_id
    }
    return render(request, 'shop/profile.html', context)


def subscription_check(request):
    return render(request, 'shop/qrcode_post_request.html')


class SubscriptionViewSet(viewsets.ModelViewSet):
    queryset = Subscription.objects.all()
    serializer_class = SubscriptionSerializer
    permission_classes = (AllowAny,)

    def list(self, request, *args, **kwargs):
        sub = self.queryset.all()
        serializer = self.serializer_class(sub, many=True)
        return Response(serializer.data, status=status.HTTP_200_OK)

    def create(self, request, *args, **kwargs):
        serializer = self.serializer_class(data=request.data)
        serializer.is_valid(raise_exception=True)
        serializer.save(request=self.request.user)
        return Response(serializer.data, status=status.HTTP_201_CREATED)

    def update(self, request, *args, **kwargs):
        partial = True
        instance = self.get_object()
        serializer = self.get_serializer(instance, data=request.data, partial=partial)
        serializer.is_valid(raise_exception=True)
        self.perform_update(serializer)
        return Response(serializer.data)


class SubscriptionSearchListAPIView(ListAPIView):
    permission_classes = (AllowAny,)
    queryset = Subscription.objects.all()
    serializer_class = SubscriptionSerializer
    filter_backends = [DjangoFilterBackend, SearchFilter]
    filterset_fields = [
        'customer', 'id'
    ]
    search_fields = [
        'customer', 'id'
    ]

shop/templates/shop/acc_active_email.html
{% autoescape off %}
Hi {{ user.username }},
Please click on the link to confirm your registration.
==========
Здравствуйте {{ user.username }}
Пожалуйста, кликните на ссылку чтобы подтвердить регистрацию.

http://{{ domain }}{% url 'users:activate' uidb64=uid token=token %}
{% endautoescape %}

shop/templates/shop/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>
        {% block title %}
        {% endblock %}
    </title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'shop/header.css' %}">
    <link rel="stylesheet" href="{% static 'shop/checkout.css' %}">
    <script type="text/javascript">
        var user = '{{request.user}}'
        var id = '{{user.id}}'

        function getToken(name) {
            let cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                const cookies = document.cookie.split(';');
                for (let i = 0; i < cookies.length; i++) {
                    const cookie = cookies[i].trim();
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
        const csrftoken = getToken('csrftoken');
    </script>
</head>
<body>
<div class="main_wrapper">
    <div class="signup_container">
      <div class="signup_header__menu">
        <ul class="signup_header__list left">
          <li>
            <a href="/" class="signup_header__link">Главная</a>
          </li>
          <li>
              {% if not user_id %}
                <a href="/users/signup/" class="signup_header__link">Профиль</a>
              {% else %}
                <a href="/user/profile/{{user_id}}/" class="signup_header__link">Профиль</a>
              {% endif %}
          </li>
          <li>
            <a href="/#gallery" class="signup_header__link">Галерея</a>
          </li>
          <li>
        </ul>
        <img src="{% static 'shop/img/Logos/VectorheaderLogo.svg' %}" alt="" class="header_logo">
        <ul class="signup_header__list right">
          <li>
            <a href="/#contacts" class="signup_header__link">Контакты</a>
          </li>
          <li>
            <a href="/shop" class="signup_header__link">Магазин</a>
          </li>
          <li>
            <a href="/user/cart/" class="signup_header__link">Корзина</a>
          </li>
        </ul>
      </div>
    </div>
</div>

<div class="wrapper">
  <div class="container">
      <div class="header">
          <div class="header__body">
              <a href="#" class="header__logo">
                  <img id="logo" src="{% static 'shop/img/Logos/WS@72x-8.png' %}">
              </a>
              <div class="header__burger">
                  <span></span>
              </div>
              <nav class="header__menu">
                  <ul class="header__list">
                      <li>
                          <a href="/" class="header__link">Главная</a>
                      </li>
                      <li>
                          {% if not user_id %}
                            <a href="/users/signup/" class="header__link">Профиль</a>
                          {% else %}
                            <a href="/user/profile/{{user_id}}/" class="header__link">Профиль</a>
                          {% endif %}
                      </li>
                      <li>
                          <a href="/#gallery" class="header__link">Галерея</a>
                      </li>
                      <li>
                          <a href="/#contacts" class="header__link">Контакты</a>
                      </li>
                      <li>
                          <a href="/shop" class="header__link">Магазин</a>
                      </li>
                      <li>
                          <a href="/user/cart/" class="header__link">Корзина</a>
                      </li>
                  </ul>
              </nav>
          </div>
      </div>
  </div>
</div>

{% block content %}

{% endblock %}
</body>
</html>

shop/templates/shop/checkout.html
{% extends 'shop/shop.html' %}

{% block title %}
Оформление заказа
{% endblock %}


{% block content %}
<div class="checkout-container">
    <div class="form">
        <form action=""  id="form">
            <div class="user-info" id="user-info">
                <div class="form-field">
                    <input type="text" class="form-control" name="name" placeholder="Имя" required>
                </div>
                <div class="form-field">
                    <input type="email" class="form-control" name="email" placeholder="Email" required>
                </div>
            </div>
            <div id="shipping-info" class="shipping-info">
                <hr>
                <h5>Информация о доставке</h5>
                <hr>
                <div class="form-field">
                    <input type="text" class="form-control" name="address" placeholder="Адрес" required>
                </div>
                <div class="form-field">
                    <input type="text" class="form-control" name="city" placeholder="Город" required>
                </div>
                <div class="form-field">
                    <input type="text" class="form-control" name="state" placeholder="Регион" required>
                </div>
                <div class="form-field">
                    <input type="text" class="form-control" name="zipcode" placeholder="Почтовый индекс" required>
                </div>
            </div>
            <hr>
            <div class="submit-button">
                <input type="submit" id="form-button" class="shipping-button" value="Продолжить">
            </div>
        </form>
    </div>

    <div class="items">
        <hr>
        <h5>Суммарный заказ</h5>
        <table class="checkout-table">
                <tr class="products-row">
                    <th colspan="2">Товар</th>
                    <th>Цена</th>
                    <th>Кол-во</th>
                    <th>Всего</th>
                </tr>
            {% for item in items %}
                <tr class="products-row">
                    <th><img class="table__image" src="{{item.product.imageURL}}" alt="product image"></th>
                    <th>{{ item.product.name }}</th>
                    <th>{{ item.product.price|floatformat:2}} сом</th>
                    <th>{{ item.quantity }}</th>
                    <th>{{ item.get_total|floatformat:2 }} сом</th>
                </tr>
            {% endfor %}
        </table>
        <div class="summary">
            <h5>Товаров: {{ cart_items }} шт.</h5>
            <h5>На сумму: {{ order.get_cart_total|floatformat:2 }} сом</h5>
            <hr>
            <a href="/user/cart/">Назад в корзину</a>
        </div>
    </div>

    <div class="payment hidden" id="payment-info">
<!--        <h4>PayPal</h4>-->
<!--        <div class="paypal-button-container" id="paypal-button-container"></div>-->
        <div class="success">
            Спасибо за ваш заказ!<br>
            Наш администратор свяжется с вами в ближайшее время!
        </div>
    </div>
</div>

<script src="http://www.paypal.com/sdk/js?client-id=sb&currency=USD"></script>

<script>
    var total = '{{order.get_cart_total}}'
    // Render the PayPal button into #paypal-button-container
    paypal.Buttons({

        style: {
            color: 'black',
            shape: 'rect'
        },

        // Set up the transaction
        createOrder: function(data, actions) {
            return actions.order.create({
                purchase_units: [{
                    amount: {
                        value: parseFloat(total).toFixed(2)
                    }
                }]
            });
        },

        // Finalize the transaction
        onApprove: function(data, actions) {
            return actions.order.capture().then(function(details) {
                // Show a success message to the buyer
                submitFormData();
            });
        }
    }).render('#paypal-button-container');
</script>

<script>
    var shipping = '{{order.shipping}}';
    var user = '{{request.user}}';

    if (user != 'AnonymousUser') {
        document.getElementById('user-info').innerHTML = '';
    }

    var form = document.getElementById('form');

    form.addEventListener('submit', function(e) {
        e.preventDefault();
        console.log('Form submitted...');
        document.getElementById('form-button').classList.add('hidden');
        document.getElementById('payment-info').classList.remove('hidden');
    });

<!--    document.getElementById('make-payment').addEventListener('click', function(e){-->
<!--        submitFormData();-->
<!--    })-->
    function submitFormData () {
        console.log('Payment button clicked')

        var userFormData = {
            'name': null,
            'email': null,
            'total': total,
        }

        var shippingInfo = {
            'address': null,
            'city': null,
            'state': null,
            'zipcode': null,
        }

        if (shipping != 'False') {
            shippingInfo.address = form.address.value
            shippingInfo.city = form.city.value
            shippingInfo.state = form.state.value
            shippingInfo.zipcode = form.zipcode.value
        }
        if (user == 'AnonymousUser') {
            userFormData.name = form.name.value
            userFormData.email = form.email.value
        }

        var url = '/process-order/'
        fetch(url, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'X-CSRFToken': csrftoken,
            },
            body: JSON.stringify({'form': userFormData, 'shipping': shippingInfo})
        })
        .then((response) => response.json())
        .then((data) => {
            console.log('Success:', data);
            alert('Transaction completed');

            cart = {};
            document.cookie = 'cart=' + JSON.stringify(cart) + ';domain=;path=/';

            window.location.href = "{% url 'shop:home' %}";
        })
    }
</script>
{% endblock %}

shop/templates/shop/login.html
{% extends 'shop/registration.html' %}
{% load static %}
{% block content %}
<div class="content">
  <div class="content__container" id="signup">
    <img class="signup_logo" src="{% static 'shop/img/Logos/GS@72x-8.png' %}" alt="">
    <h2 class="welcome">Добро пожаловать в <br> здоровый образ жизни!</h2>
    <h2 class="signup">Вход</h2>
    <form action="" method="post" class="signup__form">
      {% csrf_token %}
      <h3 class="account">{{message}}</h3>
      <input type="text" name="username" placeholder="Email">
      <input type="password" name="password" placeholder="Пароль">
      <button type="submit">Войти</button>
      <h3 class="account">Нет аккаунта?</h3>
      <a href="/users/signup" data-toggle="tab" class="account_link">Регистрация</a>
      <div class="conditions">
        <p>Продолжая, Вы принимаете наши<br>
          <a href="" class="conditions_link">Условия конфиденциальности</a>
        </p>
      </div>
    </form>
  </div>
</div>
{% endblock %}

shop/templates/shop/qrcode_post_request.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% load static %}
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'shop/qr_css.css' %}" />
    <title>Абонемент</title>
  </head>
  <body>
    <div class="result-container" id="abonementScanResult">
      <img src="{% static 'shop/img/loaders/loader.png' %}" class="abonement-loader" />
    </div>
    <script src="{% static 'shop/qr_js.js' %}"></script>
  </body>
</html>

shop/templates/shop/registration.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width">
    <title>Registration</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'shop/registration.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>
<body>
    <div class="main_wrapper">
      <div class="signup_container">
        <div class="signup_header__menu">
          <ul class="signup_header__list left">
            <li>
              <a href="/" class="signup_header__link">Главная</a>
            </li>
            <li>
              {% if not user_id %}
                  <a href="/users/signup/" class="signup_header__link">Профиль</a>
              {% else %}
                  <a href="/user/profile/{{user_id}}/" class="signup_header__link">Профиль</a>
              {% endif %}
            </li>
            <li>
              <a href="/#gallery" class="signup_header__link">Галерея</a>
            </li>
            <li>
          </ul>

          <ul class="signup_header__list right">
            <li>
              <a href="/#contacts" class="signup_header__link">Контакты</a>
            </li>
            <li>
              <a href="/shop" class="signup_header__link">Магазин</a>
            </li>
            <li>
              <a href="/user/cart/" class="signup_header__link">Корзина</a>
            </li>
          </ul>
        </div>
      </div>
    </div>


    <div class="wrapper">
        <div class="container">
            <div class="header">
                <div class="header__body">
                    <a href="#" class="header__logo">
                        <img id="logo" src="{% static 'shop/img/Logos/WS@72x-8.png' %}">
                    </a>
                    <div class="header__burger">
                        <span></span>
                    </div>
                    <nav class="header__menu">
                        <ul class="header__list">
                            <li>
                                <a href="/" class="header__link">Главная</a>
                            </li>
                            <li>
                                {% if not user_id %}
                                    <a href="/users/signup/" class="header__link">Профиль</a>
                                {% else %}
                                    <a href="/user/profile/{{user_id}}/" class="header__link">Профиль</a>
                                {% endif %}
                            </li>
                            <li>
                                <a href="/#gallery" class="header__link">Галерея</a>
                            </li>
                            <li>
                                <a href="/#contacts" class="header__link">Контакты</a>
                            </li>
                            <li>
                                <a href="/shop" class="header__link">Магазин</a>
                            </li>
                            <li>
                                <a href="/user/cart/" class="header__link">Корзина</a>
                            </li>
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </div>


    {% block content %}
    <div class="content">
      <div class="content__container" id="signup">
        <img class="signup_logo" src="{% static 'shop/img/Logos/GS@72x-8.png' %}" alt="">
        <h2 class="welcome">Добро пожаловать в <br> здоровый образ жизни!</h2>
        <h2 class="signup">Регистрация</h2>
        <form action="" method="post" class="signup__form">
          {% csrf_token %}
          {% if messages %}
              {% for message in messages %}
              <p class="{{ message.tags }}">{{message}}</p>
              {% endfor %}
          {% endif %}
          {{ signup.email }} <br>
          {{ signup.username }} <br>
          {{ signup.password1 }} <br>
          {{ signup.password2}} <br>
          <button type="submit">Зарегистрироваться</button>
          <h3 class="account">Уже есть аккаунт?</h3>
          <a href="/users/login" data-toggle="tab" class="account_link">Войти</a>
          <div class="conditions">
            <p>Продолжая, Вы принимаете наши<br>
              <a href="" class="conditions_link">Условия конфиденциальности</a>
            </p>
          </div>
        </form>
      </div>
    </div>
    {% endblock %}




    <script src="{% static 'shop/jquery/jQuery.min.js' %}"></script>
    <script src="{% static 'shop/header.js' %}"></script>
</body>
</html>

shop/templates/shop/train_construct.html
{% extends 'api/home.html' %}
{% block content %}
Ok
{% endblock %}